### ISSUE TITLE
Website difference between local and remote

### ISSUE THREAD

**Issue by FabianSchuetze** [RLEcon/website-test.github.io#2]
The website looks differently when I open it on the server compared to how it look when I open it locally. 

When I type `firefox docs/index.html` the following website pops up:

![image](https://user-images.githubusercontent.com/10357496/93197326-c781c580-f74b-11ea-8181-e7a5487c7ec7.png)

When I open the [website url](https://rlecon.github.io/website-test.github.io/html/index.html) I see (both with firefox and with chrome):
![image](https://user-images.githubusercontent.com/10357496/93197131-90131900-f74b-11ea-9686-d19253304a11.png)

How these the remote website looks like when you open it?

**Comment by jbrogueira** [comment]
Thanks. I had noticed this issue too. I am trying to fix it, but still don't know why it happens.

**Comment by FabianSchuetze** [comment]
Ok, its good to know that we saw the same public (remote) website. Thank you for taking care of it!

**Comment by jbrogueira** [comment]
In order to use github pages and the folder 'docs' as the directory where the website lives, I had to create an index file that points to the actual index in the folder docs/html. It seems that this is preventing the theme to be displayed correctly. 

I will try to find a way around this.

**Comment by FabianSchuetze** [comment]
Working :-)
